const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const read=name=>fs.readFileSync(path.join(__dirname,name),'utf8');
const source=read('core.js').replace(/export /g,'')+'\n'+read('index.js').replace(/^import .*;\n/,'').replace(/export /g,'');
const key='st_global_prompt_toggle_v1';
const old={enabled:true,text:'기존 지시문',position:'custom',depth:3,role:1,includeQuiet:false};
const host={extensionSettings:{[key]:structuredClone(old)},extensionPrompts:{[key]:{value:'stale'},other:{value:'keep'}},saves:0,
 saveSettingsDebounced(){this.saves++},setExtensionPrompt(k,text,position,depth,scan,role){this.extensionPrompts[k]={text,position,depth,scan,role}}};
const sandbox={console,structuredClone,SillyTavern:{getContext:()=>host},document:{readyState:'loading',addEventListener(){}}};vm.createContext(sandbox);vm.runInContext(source,sandbox);
const run=(type='normal')=>sandbox.stGlobalPromptToggleInterceptor([],4096,()=>assert.fail('unexpected abort'),type);
const own=()=>Object.entries(host.extensionPrompts).filter(([k])=>k.startsWith(key+':')).map(([,v])=>v);
run();assert.equal(own()[0].text,old.text);assert.equal(own()[0].depth,3);assert.equal(own()[0].role,1);assert.equal(host.extensionPrompts[key],undefined);
assert.deepEqual(JSON.parse(JSON.stringify(host.extensionSettings[key].legacyV1)),old);assert.equal(host.saves,1);
let s=host.extensionSettings[key];s.items.push(sandbox.newItem({title:'둘',text:'두 번째',enabled:true,position:'custom',depth:3,role:1}),sandbox.newItem({text:'세 번째',enabled:true,position:'before',role:0}));
run();assert.equal(own().length,2);assert.equal(own()[0].text,'기존 지시문\n\n두 번째');
s=host.extensionSettings[key];[s.items[0],s.items[1]]=[s.items[1],s.items[0]];run();assert.equal(own()[0].text,'두 번째\n\n기존 지시문');
s=host.extensionSettings[key];s.items[0].enabled=false;run();assert.equal(own()[0].text,'기존 지시문');
s=host.extensionSettings[key];s.items.splice(1,1);run();assert.equal(own().length,1);assert.equal(own()[0].text,'세 번째');
for(let i=0;i<20;i++)run();assert.equal(own().length,1);assert.equal(host.extensionPrompts.other.value,'keep');
run('quiet');assert.equal(own().length,0);run('swipe');assert.equal(own().length,1);
s=host.extensionSettings[key];s.includeQuiet=true;run('quiet');assert.equal(own().length,1);
s=host.extensionSettings[key];s.enabled=false;for(const type of ['normal','continue','regenerate','quiet','swipe']){run(type);assert.equal(own().length,0)}
assert.equal(host.extensionSettings[key].items[1].enabled,true);
host.extensionSettings[key].enabled=true;host.extensionSettings=JSON.parse(JSON.stringify(host.extensionSettings));host.extensionPrompts={};run();assert.equal(own().length,1);
s=host.extensionSettings[key];s.items[1].text=' ';run();assert.equal(own().length,0);
s=host.extensionSettings[key];s.items[1].text='valid';s.items[1].position='custom';s.items[1].depth=10001;run();assert.equal(own()[0].depth,10000);
host.extensionSettings[key].items[1].depth=-5;run();assert.equal(own()[0].depth,0);
sandbox.onDisable();run();assert.equal(own().length,0);
const migratedOff=sandbox.normalize({...old,enabled:false});assert.equal(migratedOff.items[0].enabled,false);
const empty=sandbox.normalize({schemaVersion:2,enabled:true,items:[]});assert.equal(empty.items.length,0);
console.log('PASS: v1 migration and backup, multiple instructions, grouped order, individual OFF, deletion cleanup, repeat deduplication, unrelated prompts, Quiet, master OFF preserves item states, JSON restore, blank exclusion, depth limits, disable, empty collection. Host API mocked.');
